### ISSUE TITLE
Provide a .classpath file for Eclipse

### ISSUE THREAD

**Issue by gouessej** [tordanik/OSM2World#1]
Hi

Your project would be easier to use with Eclipse if you provided a .classpath file like this one:
<?xml version="1.0" encoding="UTF-8"?>
< classpath >
    < classpathentry kind="src" path="src"/ >
    < classpathentry kind="src" path="test"/ >
    < classpathentry kind="lib" path="lib/configuration/commons-collections-3.2.1.jar"/ >
    < classpathentry kind="lib" path="lib/configuration/commons-configuration-1.6.jar"/ >
    < classpathentry kind="lib" path="lib/configuration/commons-lang-2.6.jar"/ >
    < classpathentry kind="lib" path="lib/configuration/commons-logging-1.1.1.jar"/ >
    < classpathentry kind="lib" path="lib/guava/guava-r08.jar"/ >
    < classpathentry kind="lib" path="lib/javaproj/javaproj-1.0.6.jar"/ >
    < classpathentry kind="lib" path="lib/jewelcli/jewelcli-0.6.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/gluegen-rt-natives-linux-amd64.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/gluegen-rt-natives-linux-i586.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/gluegen-rt-natives-macosx-universal.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/gluegen-rt-natives-windows-amd64.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/gluegen-rt-natives-windows-i586.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/gluegen-rt.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/jogl-all-natives-linux-amd64.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/jogl-all-natives-linux-i586.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/jogl-all-natives-macosx-universal.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/jogl-all-natives-windows-amd64.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/jogl-all-natives-windows-i586.jar"/ >
    < classpathentry kind="lib" path="lib/jogl/jogl.all.jar"/ >
    < classpathentry kind="lib" path="lib/jts/jts-1.11.jar"/ >
    < classpathentry kind="lib" path="lib/osmosis/commons-compress-1.2.jar"/ >
    < classpathentry kind="lib" path="lib/osmosis/osmosis-core-0.40.1.jar"/ >
    < classpathentry kind="lib" path="lib/osmosis/osmosis-pbf-0.40.1.jar"/ >
    < classpathentry kind="lib" path="lib/osmosis/osmosis-xml-0.40.1.jar"/ >
    < classpathentry kind="lib" path="lib/osmosis/osmpbf-1.1.1-754a33af.jar"/ >
    < classpathentry kind="lib" path="lib/osmosis/protobuf-java-2.4.1.jar"/ >
    < classpathentry kind="lib" path="lib/osmosis/xercesImpl-2.9.1.jar"/ >
    < classpathentry kind="lib" path="lib/trove/trove-111118193120.jar"/ >
    < classpathentry kind="lib" path="lib/trove/trove-3.0.1-src.jar"/ >
    < classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/ >
    < classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/4"/ >
    < classpathentry kind="output" path="bin"/ >
< /classpath >

Best regards and keep up the good work.

**Comment by tordanik** [comment]
As of 5626ba8, OSM2World is built using Maven rather than Ant. Using Eclipse's "Import existing maven project" feature should set up the classpath correctly based on the information in the pom.xml file.
