### ISSUE TITLE
Render railway=subway with tunnel=no like normal railway 

### ISSUE THREAD

**Issue by versat** [tordanik/OSM2World#100]
tunnel=no means that the subway is above ground. Thus it should be rendered accordingly. In Nürnberg for example there is some subway above the ground but not rendered by OSM2World. Since it seems to be correctly tagged and it is rendered in F4map i guess it is simply not yet implemented.

**Comment by tordanik** [comment]
Hi, thanks for the hint! This is an easy task (one or two lines of code) and I'm going to add this once I'm finished with #99.

I assume it's ok to render these just like normal rails?

**Comment by versat** [comment]
Yes i would say that is absolutely ok, i see no reason to render this in a special way.

**Comment by tordanik** [comment]
I fixed this just now, railway=subway is now rendered like normal railways.

The solution I used was to support them both over-, and underground, but allow rendering of underground subways to be switched off with the existing "renderUnderground" configuration option. 

On map.osm2world.org, "renderUnderground" is set to false, i.e. only overground subways will appear there.
