### ISSUE TITLE
crash after n reloads

### ISSUE THREAD

**Issue by Matthias84** [tordanik/OSM2World#11]
There seems to be a bug in the current SVN which causes a crash on my usual workflow:
1. Open JOSM while editing, save a local .OSM
2. Open the .OSM with O2W
3. Do further edits and reload O2W from time to time, to check the results

Sadly this results in  crashes from time to time (~ <20mins) but I have no idea how I can assist you on finding the bug.

Here is the console log: http://pastebin.com/DQMFrHby
Here is the stack trace dump: http://pastebin.com/9vnFXxPd

**Comment by tordanik** [comment]
I can no longer reproduce this with current OSM2World versions. In particular, texture support (which is now enabled by default) does not prevent a successful reload.
