### ISSUE TITLE
Missing building Parts - OSM2Cesium

### ISSUE THREAD

**Issue by stirringhalo** [tordanik/OSM2World#111]
I've figured out a path to get [OSM into Cesium](https://github.com/stirringhalo/osm2cesium) but I've run into difficulty with missing parts of buildings. For example, ![](https://cloud.githubusercontent.com/assets/14035518/16546503/8a0436ca-411a-11e6-9d9e-f56e62df79da.png) the One World Trade Center is missing the top.

Any thoughts? My .properties file is [here](https://raw.githubusercontent.com/stirringhalo/osm2cesium/29656becdb93a844fcd4271aaea151d855a0fd7a/prop.properties) and osm2world is called [here](https://raw.githubusercontent.com/stirringhalo/osm2cesium/bdee71d143a68d903e90ac9df52d0009dcfc7a2f/osm2cesium.sh)

**Comment by tordanik** [comment]
It seems as if you get rid of building parts with your `--tf accept-ways "building=*"` filter. For building rendering, at least building=* and building:part=* are needed.

**Comment by stirringhalo** [comment]
You're quite right, I identified my osmosis filter was tossing those features out but forgot to close this issue.
