### ISSUE TITLE
Coordinate System

### ISSUE THREAD

**Issue by stirringhalo** [tordanik/OSM2World#114]
I'm looking to feed .objs from OSM2World into FME and am looking to understand the output coordinate system.

Could you speak to the internal coordinate transformation that occurs?

I need to handle the following projection parameters in the FME tool, so any guesses/help would be awesome:

Projection Type (I think Lambert Azimuthal Equidistant)
Projection Units (likely meters?)
Origin Coordinate System (I'm stumped by this one, what )
Origin X and Y (whatever I define to be 0,0 in the input, so I will just put it as 0,0)

If not, I can do an affine transform and guarantee the projection will be correct. 

Thanks!

**Comment by tordanik** [comment]
In the .objs, the coordinate origin is given as a comment at the beginning of the file. The units are meters in each dimension. Hope that helps.

**Comment by stirringhalo** [comment]
That indeed does, I forgot about that when I opened this. I've been using it rather successfully.
