### ISSUE TITLE
building:part that is entirely inside another building not rendered

### ISSUE THREAD

**Issue by m93a** [tordanik/OSM2World#119]
Steps to reproduce:
1) Open JOSM, add a new layer
2) Create an area and tag it `building=yes; height=1`
3) Create another area inside this one so that it shares only one node
4) Tag it `building:part=yes; height=2`
5) Optionally add them to a relation of `type=building`
6) Save and open with OSM2World

Result:
Sometimes the `building:part` won't get rendered.
I managed to create a minimal example, see the attachment.

[bug.zip](https://github.com/tordanik/OSM2World/files/706853/bug.zip)

**Comment by m93a** [comment]
Sorry, my mistake 😀 The latest beta works great!

**Comment by tordanik** [comment]
Thanks for error-checking OSM2World! Feel free to add more issues if you notice anything, I'm sure there are plenty of bugs to be found.

As this seems to have been a false alarm, I'm closing the issue.
