### ISSUE TITLE
Accept *:color=* as well

### ISSUE THREAD

**Issue by Matthias84** [tordanik/OSM2World#13]
As Simple Building Model introduces various possibilities to style building parts, it suggests to make use on the colour=\* tags (UK spelling) which is absolutly right. But as here in Germany for example the "color" term is much more popular, the mapper might use it instead.

So I recommend to support all color attributes with simple "color" as legacy fallback option and maybe to report the misspelling of the tags, if found.

**Comment by tordanik** [comment]
Although still present in the database, the proportion of misspelled colour values has gradually declined over the past four years. Due to this, I no longer see a need to support alternative spellings.
