### ISSUE TITLE
Unable to compile (missing ExtrudeOption, PolylineXZ)

### ISSUE THREAD

**Issue by Sam-Lowry** [tordanik/OSM2World#130]
Since commit bb38278434a42780cad08e1000ea386a0d848ebc trying to compile gives the errors below. The last commit that compiles is 49bfb76ba79e535d6db6681d3bbce5b1bb875c6c

    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/target/Target.java:15: error: cannot find symbol
    [javac] import org.osm2world.core.target.common.ExtrudeOption;
    [javac]                                        ^
    [javac]   symbol:   class ExtrudeOption
    [javac]   location: package org.osm2world.core.target.common
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/target/Target.java:134: error: cannot find symbol
    [javac] 			List<VectorXYZ> upVectors, List<Double> scaleFactors, EnumSet<ExtrudeOption> options);
    [javac] 			                                                              ^
    [javac]   symbol:   class ExtrudeOption
    [javac]   location: interface Target<R>
    [javac]   where R is a type-variable:
    [javac]     R extends Renderable declared in interface Target
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/target/common/AbstractTarget.java:8: error: cannot find symbol
    [javac] import static org.osm2world.core.target.common.ExtrudeOption.*;
    [javac]                                               ^
    [javac]   symbol:   class ExtrudeOption
    [javac]   location: package org.osm2world.core.target.common
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/target/common/AbstractTarget.java:78: error: cannot find symbol
    [javac] 			List<VectorXYZ> upVectors, List<Double> scaleFactors, EnumSet<ExtrudeOption> options) {
    [javac] 			                                                              ^
    [javac]   symbol:   class ExtrudeOption
    [javac]   location: class AbstractTarget<R>
    [javac]   where R is a type-variable:
    [javac]     R extends Renderable declared in class AbstractTarget
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/target/common/AbstractTarget.java:185: error: cannot find symbol
    [javac] 	private static final EnumSet<ExtrudeOption> DEFAULT_EXTRUDE_OPTIONS = EnumSet.noneOf(ExtrudeOption.class);
    [javac] 	                             ^
    [javac]   symbol:   class ExtrudeOption
    [javac]   location: class AbstractTarget<R>
    [javac]   where R is a type-variable:
    [javac]     R extends Renderable declared in class AbstractTarget
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/BarrierModule.java:9: error: cannot find symbol
    [javac] import static org.osm2world.core.target.common.ExtrudeOption.*;
    [javac]                                               ^
    [javac]   symbol:   class ExtrudeOption
    [javac]   location: package org.osm2world.core.target.common
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/BarrierModule.java:29: error: cannot find symbol
    [javac] import org.osm2world.core.math.shapes.PolylineXZ;
    [javac]                                      ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: package org.osm2world.core.math.shapes
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/PoolModule.java:33: error: cannot find symbol
    [javac] import org.osm2world.core.math.shapes.PolylineXZ;
    [javac]                                      ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: package org.osm2world.core.math.shapes
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/PowerModule.java:29: error: cannot find symbol
    [javac] import org.osm2world.core.math.shapes.PolylineXZ;
    [javac]                                      ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: package org.osm2world.core.math.shapes
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/RailwayModule.java:22: error: cannot find symbol
    [javac] import org.osm2world.core.math.shapes.PolylineXZ;
    [javac]                                      ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: package org.osm2world.core.math.shapes
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/RoadModule.java:39: error: cannot find symbol
    [javac] import org.osm2world.core.math.shapes.PolylineXZ;
    [javac]                                      ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: package org.osm2world.core.math.shapes
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/WaterModule.java:32: error: cannot find symbol
    [javac] import org.osm2world.core.math.shapes.PolylineXZ;
    [javac]                                      ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: package org.osm2world.core.math.shapes
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/target/common/AbstractTarget.java:169: error: cannot find symbol
    [javac] 			if (options.contains(START_CAP)) {
    [javac] 			                     ^
    [javac]   symbol:   variable START_CAP
    [javac]   location: class AbstractTarget<R>
    [javac]   where R is a type-variable:
    [javac]     R extends Renderable declared in class AbstractTarget
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/target/common/AbstractTarget.java:174: error: cannot find symbol
    [javac] 			if (options.contains(END_CAP)) {
    [javac] 			                     ^
    [javac]   symbol:   variable END_CAP
    [javac]   location: class AbstractTarget<R>
    [javac]   where R is a type-variable:
    [javac]     R extends Renderable declared in class AbstractTarget
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/target/common/AbstractTarget.java:185: error: cannot find symbol
    [javac] 	private static final EnumSet<ExtrudeOption> DEFAULT_EXTRUDE_OPTIONS = EnumSet.noneOf(ExtrudeOption.class);
    [javac] 	                                                                                     ^
    [javac]   symbol:   class ExtrudeOption
    [javac]   location: class AbstractTarget<R>
    [javac]   where R is a type-variable:
    [javac]     R extends Renderable declared in class AbstractTarget
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/BarrierModule.java:152: error: cannot find symbol
    [javac] 					nCopies(getCenterline().size(), Y_UNIT),null, EnumSet.of(START_CAP, END_CAP));
    [javac] 					                                                         ^
    [javac]   symbol:   variable START_CAP
    [javac]   location: class ColoredWall
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/BarrierModule.java:152: error: cannot find symbol
    [javac] 					nCopies(getCenterline().size(), Y_UNIT),null, EnumSet.of(START_CAP, END_CAP));
    [javac] 					                                                                    ^
    [javac]   symbol:   variable END_CAP
    [javac]   location: class ColoredWall
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/BarrierModule.java:375: error: cannot find symbol
    [javac] 		private static ShapeXZ SHAPE_GERMAN_B = new PolylineXZ(
    [javac] 		                                            ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: class Guardrail
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/BarrierModule.java:386: error: cannot find symbol
    [javac] 		private static ShapeXZ SHAPE_POST_DOUBLE_T = new PolylineXZ(
    [javac] 		                                                 ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: class Guardrail
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/BarrierModule.java:430: error: cannot find symbol
    [javac] 			target.drawExtrudedShape(material, new PolylineXZ(reverse(SHAPE_GERMAN_B.getVertexList())),
    [javac] 			                                       ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: class Guardrail
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/BarrierModule.java:466: error: cannot find symbol
    [javac] 							nCopies(boltPath.size(), Y_UNIT), null, EnumSet.of(END_CAP));
    [javac] 							                                                   ^
    [javac]   symbol:   variable END_CAP
    [javac]   location: class Guardrail
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/BarrierModule.java:524: error: cannot find symbol
    [javac] 						nCopies(2, Y_UNIT), null, EnumSet.of(START_CAP, END_CAP));
    [javac] 						                                     ^
    [javac]   symbol:   variable START_CAP
    [javac]   location: class JerseyBarrier
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/BarrierModule.java:524: error: cannot find symbol
    [javac] 						nCopies(2, Y_UNIT), null, EnumSet.of(START_CAP, END_CAP));
    [javac] 						                                                ^
    [javac]   symbol:   variable END_CAP
    [javac]   location: class JerseyBarrier
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/PoolModule.java:156: error: cannot find symbol
    [javac] 			ShapeXZ wallShape = new PolylineXZ(
    [javac] 			                        ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: class Pool
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/PoolModule.java:198: error: cannot find symbol
    [javac] 			CROSS_SECTION_PIPE = new PolylineXZ(crossSection);
    [javac] 			                         ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: class WaterSlide
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/PowerModule.java:311: error: cannot find symbol
    [javac] 			ShapeXZ powerlineShape = new PolylineXZ(
    [javac] 			                             ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: class PowerMinorLine
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/RailwayModule.java:107: error: cannot find symbol
    [javac] 			RAIL_SHAPE = new PolylineXZ(railShape);
    [javac] 			                 ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: class Rail
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/RoadModule.java:766: error: cannot find symbol
    [javac] 		protected static final ShapeXZ HANDRAIL_SHAPE = new PolylineXZ(
    [javac] 		                                                    ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: class Road
    [javac] /Users/diego/projects/OSM2World/src/org/osm2world/core/world/modules/WaterModule.java:325: error: cannot find symbol
    [javac] 			ShapeXZ wallShape = new PolylineXZ(
    [javac] 			                        ^
    [javac]   symbol:   class PolylineXZ
    [javac]   location: class AreaFountain
    [javac] 29 errors

**Comment by tordanik** [comment]
Thanks a lot for spotting this one! Turns out I had forgotten to add these files to the commit ... oops. Fixed in 0723ed1630a356f1dd4e9f91496e315cf31df284
