### ISSUE TITLE
french language LANG creates invalid .obj.mtl files

### ISSUE THREAD

**Issue by artlog** [tordanik/OSM2World#137]
First of all thank for that wonderful tool. I will use it to 3D print a french village ( valbonne ).
It took me some time to get it right because with default french LANG the .obj.mtl file contains taht :+1: 

___
# This file was created by OSM2World 0.2.0 - http://osm2world.org

newmtl MAT_0_0
Ns 92.156863
Ka 0.39215687 0.39215687 0.39215687
Kd 0.39215687 0.39215687 0.39215687
Ks 0,000000 0,000000 0,000000
Ke 0,000000 0,000000 0,000000
Ni 1
illum 2
_____

french separator for decimal is ',' and not a '.' what confuse then blender when importing it.

problem lies in org.osm2world.core.target.obj.ObjTarget where %F is used and that one use ',' for LANG=FR

			mtlStream.println(String.format("Ks %f %f %f", material.getSpecularFactor(), material.getSpecularFactor(), material.getSpecularFactor()));
			mtlStream.println(String.format("Ke %f %f %f", 0f, 0f, 0f));

by calling program with  LANG=US java -jar build/OSM2World.jar it bypasses this problem.

**Comment by artlog** [comment]
https://docs.oracle.com/javase/8/docs/api/java/lang/String.html

is suggest to use format with a Locale set since i guess obj format is not language dependent.

**Comment by tordanik** [comment]
Fixed by merging #138.
