### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by hellocatfood** [tordanik/OSM2World#139]
I compiled the code using ant and tried to run the software by running `java -jar build/OSM2World.jar --gui`. I got the following error even when trying to run it without the gui:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/home/hellocatfood/Desktop/OSM2World/build/lib/jogl/gluegen-rt.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 112: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

I'm using ubuntu 18.10

**Comment by WarnerV** [comment]
Just wanted to highlight: I got the same message, but only on openjdk-11-jre. After switching to openjdk-8-jre the issue disappeared.

**Comment by amoyag00** [comment]
Sadly I am using openjkd-8-jre and I still got that error. I got it working by following the instructions provided by Autar in this SO post https://stackoverflow.com/questions/10995894/worldwind-runnable-jar-no-gluegen-rt-in-java-library-path
Hope it helps!

I'm using  Ubuntu 16.04 and the version I run was the 0.1.9

**Comment by maifeeulasad** [comment]
Actually downgrading to java-8 worked for me and installing some gtk3 modules :
```
sudo apt install libcanberra-gtk-module libcanberra-gtk3-module
sudo apt-get install openjdk-8-jdk 
```
And here is the configuration for IntelliJ : 
![solution to osm2world - WARNING: An illegal reflective access operation has occurred](https://user-images.githubusercontent.com/29339330/114500760-8a7ea280-9c4a-11eb-950b-fb587c0b610b.png)
Please see this ss to : 
![solution to osm2world - WARNING: An illegal reflective access operation has occurred, specific version](https://user-images.githubusercontent.com/29339330/114501026-ff51dc80-9c4a-11eb-8a2c-7d8d4fe6d17d.png)

**Comment by Kchour** [comment]
If you have multiple Java versions installed on your machine, you can switch between them via (switching to java-8 helped):

 `$   sudo update-alternatives --config java`

This [link ](https://aboullaite.me/switching-between-java-versions-on-ubuntu-linux/)explains more. Just wanted to leave this here in case it helps anyone.

**Comment by tordanik** [comment]
As of fbe6b37, OSM2World is now using a JOGL 2.4.0 release candidate. This makes current builds compatible with modern JDK versions and should take care of the need to downgrade to java-8 to run OSM2World.
