### ISSUE TITLE
add build instruction to the readme

### ISSUE THREAD

**Issue by matkoniecz** [tordanik/OSM2World#140]
For example to even install it, instead of having instructions in readme I get

> Visit the project website at http://osm2world.org/ for documentation, downloads, screenshots and contact information!

then I need to switch to http://osm2world.org/docs/ to get

> The wiki page contains a more in-depth description and usage instructions. If you haven't read it yet, it's the first place you should go to learn more about OSM2World.

and from what I see https://wiki.openstreetmap.org/wiki/OSM2World has only https://wiki.openstreetmap.org/wiki/OSM2World linking to compiled binaries

**Comment by matkoniecz** [comment]
the simplest solution "import to Intellij IDEA, let it autoconfigure build system failed"

**Comment by tordanik** [comment]
Thanks for opening this issue! For the most part, the build instructions are "run `ant jar` in the project root" (or `ant dist` if you want zip files as the ones provided on the download page), but I agree that the readme needs to document this.
