### ISSUE TITLE
support for building:shape ?

### ISSUE THREAD

**Issue by cyclehome** [tordanik/OSM2World#143]
Hi,
is it planned to support the building:shape tag sometime in the future?

E.g. the Berlin television tower has its sphere described with <tag k="building:shape" v="sphere"/>.
So far the tower appears just as a single column in the output ...

@tordanik
Saw a video where you presented new features (OpenGL frontend) at the fossgis conference last week. Can you provide any forecast when this might be released?

Thanks a lot!

**Comment by tordanik** [comment]
The `building:shape` key is undocumented and – I believe – only supported by OSMBuildings at the moment. Its semantics (e.g. placement of entrances) aren't really clear to me, and I'm not convinced that the `building:shape=cylinder` value is preferable over a more general solution for round walls. So, at the moment, I do not have plans to implement it. But I'm open to discuss the topic, e.g. on the OSM forum. If this tag becomes more broadly accepted by the 3D community, I will of course aim to support it.

As for the WebGL frontend: It's hard to give an estimate, but probably not before May.

**Comment by cyclehome** [comment]
ok, thanks!
