### ISSUE TITLE
Add glTF as an output format

### ISSUE THREAD

**Issue by tordanik** [tordanik/OSM2World#157]
[glTF](https://en.wikipedia.org/wiki/GlTF) is a popular, modern format for 3d models. Although converting .obj to .gltf is possible, it would be preferable to support .gltf as an OSM2World output format directly.

Some considerations:
* Part of the challenge will be representing OSM2World's multi-layer, colorable materials with glTF. We could use the same workaround as with .obj files (multiple layers of partially transparent geometry), or the [KHR_techniques_webgl extension](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_techniques_webgl) for custom shader programs (which not all consumers are likely to support).
* [JglTF](https://github.com/javagl/JglTF) could be a useful dependency.
* glTF 2.0 uses PBR materials, which OSM2World would first need to add support for

**Comment by tordanik** [comment]
I've implemented glTF support in a39ae14, building on OSM2World's recently added PBR capabilities. It's working in the latest build, although some improvements are still missing (such as support for multi-layer textures and merging meshes of the same material for better performance). The feature will be part of the upcoming 0.3.0 release.

**Comment by KaiRo-at** [comment]
That sounds great, I think I'll need to take a look at some point! :)
