### ISSUE TITLE
There is ZERO instruction on how to even start this program. 

### ISSUE THREAD

**Issue by dtoxftw** [tordanik/OSM2World#159]
Kind of important...

any instruction is appreciated. thanks

**Comment by ancarda** [comment]
@dtoxftw: This page may be helpful: https://wiki.openstreetmap.org/wiki/OSM2World#How_to_use_OSM2World -- essentially, download the zip file [from the website](http://osm2world.org/download/), unpack it, and then use the terminal/command line to run `./osm2world.sh --gui`

**Comment by tordanik** [comment]
The wiki documentation pointed out by @ancarda is indeed the main resource on how to run OSM2World at the moment. It's also linked from the OSM2World website's [documentation subpage](http://osm2world.org/docs/). Admittedly, there's room for improvement!

If you need additional assistance, feel free to reach out on platforms such as the [OpenStreetMap forum](https://forum.openstreetmap.org/) or [help system](https://help.openstreetmap.org/)!
