### ISSUE TITLE
Compilation error  with latest - SimplePolygonShapeXZ class files missing

### ISSUE THREAD

**Issue by sagarjogadhenu** [tordanik/OSM2World#160]
[ERROR] /home/sagarj-cypat1/OSM2World/src/main/java/org/osm2world/core/math/AxisAlignedBoundingBoxXZ.java:[10,38] cannot find symbol
  symbol:   class SimplePolygonShapeXZ
  location: package org.osm2world.core.math.shapes

**Comment by tordanik** [comment]
Thanks a lot for spotting and reporting this issue! It should be fixed in b6b9d86.
