### ISSUE TITLE
How to generate a road interchange (bridge)?

### ISSUE THREAD

**Issue by rongguodong** [tordanik/OSM2World#167]
I tried a region from openstreetmap which includes a clover leaf interchange. But the generated mesh by OSM2World has all road flat. (I do see 3D buildings, trees, etc.) What I want is the result as show in [this screenshot](http://osm2world.org/examples/0.1.0/Autobahnkreuz%20Stuttgart%20POV.png). Can anyone tell me how to generate a road interchange correctly? Thanks a lot!

**Comment by tordanik** [comment]
The code used to generate that image is not part of the most recent version of OSM2World. The last version containing it was 0.1.9. If you're looking for this specific behavior, you can download old releases here:
http://osm2world.org/download/files/
(Fair warning: It doesn't look as good from close up.)

Current versions of OSM2World have an all-new logic for elevation calculation that's still experimental. You can enable it by setting the EleConstraintEnforcer to "Simple" in the options. Unfortunately, it doesn't handle intersections well yet, producing implausibly steep ramps at bridges.

Overall, this is feature is still very much a work in progress.
