### ISSUE TITLE
Temporary png

### ISSUE THREAD

**Issue by frank11000** [tordanik/OSM2World#177]
Hello,
I'm try to open a scene that I exported with OSM2World and I get this error : 
![image](https://user-images.githubusercontent.com/46491082/122122070-9d6d4900-ce2c-11eb-8a3e-c8dfc2f642bd.png)
[Scene.zip](https://github.com/tordanik/OSM2World/files/6658677/Scene.zip)
I checked and the PNGs are not there.
Have you an idea why ?
Best, Frank

**Comment by tordanik** [comment]
I understand what's going on here: OSM2World supports SVG vector graphics for textures, but many output formats (including OBJ and POV) do not. To solve this discrepancy, OSM2World generates PNG raster graphics from the SVG textures. But these are created as temporary files, which get deleted after OSM2World terminates. So this solution only helps with output types such as OpenGL that make use of the textures immediately.

As glTF allows models along with all their textures to be stored in a single file, it does not suffer from this limitation. So if your use case is compatible with glTF, using that output format lets you avoid this issue.

Another possible workaround would be for you to do the SVG -> PNG conversion yourself (you'll find files such as helipad_markings.svg in a "textures" directory alongside OSM2World) and edit the output file to point to your PNGs. But that's quite laborious. (Also, this will not help with other types of textures that are generated by OSM2World during the program's run, such as procedural textures.)

A proper fix in OSM2World will be to place the PNG files in a non-temporary location, e.g. in the directory of the output file, and point the path in the output file to that location.

**Comment by tordanik** [comment]
Fixed in bf3d314 by placing all required textures in a texture directory next to the .obj file.

Thanks for the bug report!
