### ISSUE TITLE
"Please port CPU detection to your platform" Error with M1 Chip

### ISSUE THREAD

**Issue by endim8** [tordanik/OSM2World#185]
Trying to run OSM2World on an M1 mac results in this error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at javax.media.opengl.GLProfile.<clinit>(GLProfile.java:82)
	at org.osm2world.viewer.view.ViewerFrame.createCanvas(ViewerFrame.java:340)
	at org.osm2world.viewer.view.ViewerFrame.<init>(ViewerFrame.java:119)
	at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
	at org.osm2world.console.OSM2World.main(OSM2World.java:144)
Caused by: java.lang.RuntimeException: Please port CPU detection to your platform (mac os x/aarch64)
	at jogamp.common.os.PlatformPropsImpl.getCPUTypeImpl(PlatformPropsImpl.java:166)
	at jogamp.common.os.PlatformPropsImpl.<clinit>(PlatformPropsImpl.java:95)
	... 5 more

```

I did some research, and it seems to be an issue with GlueGen being an old version (2.0.2). According to this report, it's fixed in GlueGen 2.3.1-1 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=791993

**Comment by endim8** [comment]
tried just building with a newer version of gluegen, but unfortunately it needs some extra work

**Comment by tordanik** [comment]
Thanks for testing, this is good information as I don't have access to M1 hardware

Upgrading to JOGL 2.4.0 (and the associated gluegen) is something I want to do for other reasons, such as compatibility with modern Java versions. The main challenges are that there's no nicely packaged build of 2.4.0 in the usual maven repositories (so I'll likely end up having to bundle a build with my code), and that upgrading across multiple version jumps does involve significant changes to OSM2World's OpenGL-related code.

**Comment by endim8** [comment]
https://mvnrepository.com/artifact/org.jogamp.jogl/jogl-all-main/2.4.0

I've found this if it's any good :)

**Comment by tordanik** [comment]
> https://mvnrepository.com/artifact/org.jogamp.jogl/jogl-all-main/2.4.0

Thanks, this turned out to be an excellent hint. I was able to use that repository to upgrade to 2.4.0 by using it as a dependency as described [here](https://github.com/jzy3d/jogl-maven-deployer).

So as of fbe6b37, OSM2World is now using a JOGL 2.4.0 release candidate. Hopefully this takes care of M1 support?

**Comment by endim8** [comment]
<img width="1122" alt="Screenshot 2022-12-30 at 16 58 49" src="https://user-images.githubusercontent.com/26939824/210094803-02f1591f-8a61-413e-8c33-a34b06f90682.png">

After installing an M1-native Java8 (https://stackoverflow.com/a/73843488/13351126), it works! thank you so much 😄
