### ISSUE TITLE
Add a configuration option for left-hand traffic

### ISSUE THREAD

**Issue by tordanik** [tordanik/OSM2World#187]
Whether right-hand or left-hand traffic is the default should be controllable through a configuration option. At the moment, this still requires changing a constant in the source code.

**Comment by morishima0524** [comment]
>> I couldn’t find driving side option when execute conversion using OSM2World.
>> 
>>    https://wiki.openstreetmap.org/wiki/OSM2World/Configuration_file
>
> unfortunately, this requires changing the source code at the moment. 
> Specifically, this constant needs to be set to false instead of true:
> https://github.com/tordanik/OSM2World/blob/master/src/main/java/org/osm2world/core/world/modules/RoadModule.java#L62

I had changed and execute conversion but couldn't get expected result.
I changed only `true` to `false` like below:
`public static final boolean RIGHT_HAND_TRAFFIC_BY_DEFAULT = false;`

### Input osm (Abbreviate some elements.)
The road has 3 lanes and is left-hand traffic.
```<osm version="0.6" generator="CGImap 0.8.6 (3920265 spike-08.openstreetmap.org)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
 <bounds minlat="35.5981328" minlon="139.6096246" maxlat="35.5991328" maxlon="139.6106246"/>
...
 <way id="885553305" visible="true" version="2" changeset="96203679" timestamp="2020-12-21T15:07:45Z" user="ffff23" uid="10888797">
  <tag k="highway" v="primary"/>
  <tag k="lanes" v="3"/>
  <tag k="lanes:backward" v="1"/>
  <tag k="lanes:forward" v="2"/>
  <tag k="name:en" v="Tsurumi Mizonokuchi Line"/>
  <tag k="name:ja" v="鶴見溝ノ口線"/>
  <tag k="oneway" v="no"/>
  <tag k="ref" v="14"/>
  <tag k="route" v="road"/>
  <tag k="turn:lanes:forward" v="left;through|right"/>
 </way>
...
</osm>
```

### I expect:
- Leftmost lane have left-turn and straight-through arrow.
- Middle lane (right of forward lane) have righ-turn arrow.
- Rightmost lane have no sign.

### But I got:
- Leftmost lane had **right-turn** arrow.
- Middle lane (right of forward lane) had **left-turn and straight-through** arrow.
- Rightmost lane had no sign. (It's expected)

By the way, convert with right-hand traffic is true:
- Leftmost lane had no sign.
- Middle lane had left-turn and straight-through arrow.
- Rightmost lane had right-turn arrow.

Please use this as a reference.

**Comment by tordanik** [comment]
Thank you for looking into this more closely, this is a very useful report. With your example, I was able to easily reproduce the issue. It appears that the logic for parsing keys with a `:lane` suffix does not correctly take driving directions into account. (I believe the result of `getPerLaneTags` needs to be reversed for left-hand traffic.) I'll make sure to fix this soon.

**Comment by tordanik** [comment]
c2faa23 fixes incorrect lane arrangement for left-hand traffic.
34a2337 additionally offers a config option `drivingSide=left` that changes the default so that changes to the code itself should no longer be necessary.

I hope these commits resolve the issue, please let me know if there are still problems!
