### ISSUE TITLE
Is LGPL license applying also to all resorces/textures/models etc?

### ISSUE THREAD

**Issue by matkoniecz** [tordanik/OSM2World#189]
I am asking as I am unsure about licensing of https://wiki.openstreetmap.org/wiki/File:3D_Baum.png 

How screeshoots created using this software should be licensed?

to increase confusion http://osm2world.org/ has "All images on this page are licensed CC-by-SA 2.0 and are based on OpenStreetMap data"

**Comment by tordanik** [comment]
No, I do not consider output produced by OSM2World or screenshots of the software to be subject to any licensing restrictions. The LGPL applies only to the source code, and [the default set of textures, models and resources](https://github.com/tordanik/OSM2World-default-style) shipped with OSM2World downloads is available under the terms of the CC0 public domain dedication.

So if you use OSM2World to create models or images from geodata you have produced yourself, you can license the output as you wish. If you use it to create models or images from OpenStreetMap data, you need to follow the requirements of OpenStreetMap's ODbL license for "produced works".

**Comment by matkoniecz** [comment]
Thanks!
