### ISSUE TITLE
Other games besides SuperTuxKart?

### ISSUE THREAD

**Issue by golimarrrr** [tordanik/OSM2World#191]
I was planning on using OSM2World to make a real world map for games like Doom, Quake, Age of Empires II, Counter Strike, ...
Have any of you managed to do this?

**Comment by tordanik** [comment]
I'm not aware of any existing efforts except the SuperTuxKart one. It would be cool, and even though I'm currently focusing on improving OSM2World itself, I would of course support such efforts.

The main challenge here is that while OSM2World gives you the 3D models, there will still be specific steps necessary for each game. Especially if you want the result to be fun to play!

The games where OSM2World will be more easily integrated into a map making pipeline are those that allow you to import arbitrary 3d objects/scenes. If the game is limited to a specific set of tiles/blocks/assets (as I believe Age of Empires II is, for example), it is likely that OSM2World won't be much help.

**Comment by golimarrrr** [comment]
Agreed.

It's difficult to get a full map making pipeline like it has been done with SuperTuxKart

That's true about AoE2, and also Doom would be a problem as maps are mostly 2D and not 3D. But for those games a 2D representation of the "floor" could be useful, and one would start building from that floor up

Anyone who makes some progress with other games is welcome to share it in this issue :)
