### ISSUE TITLE
window:frame:colour

### ISSUE THREAD

**Issue by Sinuhe20** [tordanik/OSM2World#194]
Hello,

I was a bit confused why setting window:frame:colour on building (part) or window node had no effect and found out that default material is plastic and it's textured in config but with no colorable option.

So maybe `material_PLASTIC_texture0_colorable = true` should be set as default but the plastic texture is also a bit too greyish. Maybe a more white texture should be used (with default color grey, but which can be overwritten). Same problem for any painted wooden materials. So I would say if a material color is set but not *texture0_colorable for the material in the config, the texture should be deactivated and instead a plain material be shown. Because I see also no other way to use a colored plain material, when a textured default material like plastic is set.

Best regards

**Comment by tordanik** [comment]
Fixed in the style repository by setting plastic to colorable and using a white base color texture:
tordanik/OSM2World-default-style@dda6ccb

**Comment by Sinuhe20** [comment]
Thanks!
