### ISSUE TITLE
`traffic_sign`  - position and direction

### ISSUE THREAD

**Issue by vizsim** [tordanik/OSM2World#223]
Hello,

I noticed that a `traffic_sign`, which is tagged [on the way](https://wiki.openstreetmap.org/wiki/Key:traffic_sign#As_part_of_a_way), is being rendered exactly on the way and in the wrong direction.

<img width="561" alt="traffic_sign_direction-position" src="https://github.com/user-attachments/assets/318ca365-fbd8-4d6a-a737-94f895325c20">

https://www.openstreetmap.org/node/12177996731

https://www.mapillary.com/app/?lat=51.69604989999999&lng=13.248659900000007&z=19.9&pKey=2743821315777428&focus=photo&x=0.6606119587208592&y=0.6918927844675042&zoom=1.3530146441883322

In order to show this "correctly", I am not quite sure if this should be tagged in another way or if this is a bug/missing feature in osm2world, especially for "on the way"-tagging.

- Direction:  
  - As shown in the ID Editor screenshot, the given direction is correctly tagged, however osm2world does not take this into account.
<img width="417" alt="traffic_sign_direction-position_idEditor" src="https://github.com/user-attachments/assets/cb0c9317-cc0b-425c-a841-01c3bc81507c">

- Positioning: 
  - Would it be feasible to offset the position next to the way? At least in Germany the default could be on the right side of the given position of the way, as this is the recommendation by authorities ("Verkehrszeichen sind gut sichtbar in etwa rechtem Winkel zur Fahrbahn rechts daneben anzubringen", https://www.verwaltungsvorschriften-im-internet.de/bsvwvbund_26012001_S3236420014.htm ) for traffic sign positions.

##### Example `traffic_sign=city_limit`:

<img width="340" alt="traffic_sign_citylimit2" src="https://github.com/user-attachments/assets/f60e268c-ea42-434d-a2b7-c448fbd330ab">

https://www.openstreetmap.org/node/529113471 

https://www.mapillary.com/app/?lat=51.68908949708998&lng=13.254674399999999&z=17.716352794029255&pKey=187753117057510&focus=photo&dateFrom=2022-09-01&x=0.43797614338701807&y=0.5921466144140789&zoom=0.4691164972634871

A positioning offset for a  `traffic_sign=city_limit` seems to exist:
<img width="462" alt="traffic_sign_citylimit" src="https://github.com/user-attachments/assets/95623c32-83d8-4dd8-a717-b38474203e14">

**Comment by tordanik** [comment]
Thanks for the high-quality bug report which made it very easy to reproduce the issue! Fixed in 0e520adb.

There were two separate problems here: Traffic signs on ways did not work for footway/path (which is why the city_limit example worked) and `traffic_sign:direction` was not supported.

With these problems resolved, the traffic sign will now appear next to the path and face the correct direction:
![Fixed traffic_sign on way](https://github.com/user-attachments/assets/30cab535-e26a-425c-b788-28009d4a2559)

The fix will be part of the next build.
