### ISSUE TITLE
Higher treeCount default?

### ISSUE THREAD

**Issue by Matthias84** [tordanik/OSM2World#32]
Hi tried some variations and at least for me, the value 0.01 is more what I expect a wood area to look like. What you say, should we change the default value, or do you already map very small wood areas with a lower density?

**Comment by tordanik** [comment]
Tree density has defaulted to 0.01 trees/m² for quite a while, with the [default style](/tordanik/OSM2World-default-style) doubling it to 0.02 trees/m². Realistic numbers would be even higher, but that probably only makes sense alongside more fundamental improvements to vegetation rendering.
