### ISSUE TITLE
Paint turn arrows on roads

### ISSUE THREAD

**Issue by tordanik** [tordanik/OSM2World#77]
Use the [turn:lanes](http://wiki.openstreetmap.org/wiki/Key:turn) key to render painted arrows for each turn lane. Implementing this should be comparatively easy using the existing multi-texturing feature as well as the texture coordinate formulas for triangle strips introduced in 6a51889454df48c94147131b59d3559726d2291c

CC0 graphics for arrows that follow the [country-specific](http://commons.wikimedia.org/wiki/File:Fahrbahnmarkierung.png) standards are still missing.

**Comment by der-stefan** [comment]
You could further improve the rendering by drawing a solid line between the turn lane and the opposite direction.

**Comment by HolgerJeromin** [comment]
This would imply that you are not allowed to drive through. This could be the case, but there could be a small driveway which is allowed.
The corresponding tag is: http://wiki.openstreetmap.org/wiki/Proposed_features/change
