### ISSUE TITLE
Hillshading Tiles can't get loaded

### ISSUE THREAD

**Issue by davidak** [tordanik/OSM2World#90]
![bildschirmfoto 2014-10-04 um 02 13 57](https://cloud.githubusercontent.com/assets/91113/4514067/755180e0-4b5b-11e4-822b-e1b988e73b22.png)

http://maps.osm2world.org/

**Comment by tordanik** [comment]
The hillshading tiles come from Wikimedia's development servers, which were restructured at the time of this bug report. I have since changed the URL to the new address of the tiles.

I assume that the bug is therefore solved. If it persists, please reopen.

**Comment by davidak** [comment]
yes, works. thank you
